# Generated by Django 4.0.4 on 2025-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_address_area_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_Number',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
