# Generated by Django 4.0.4 on 2025-10-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_Number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
