# Generated by Django 4.0.4 on 2025-10-21 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='El formato debe ser +56912345678', regex='\\+569\\d{8}$')]),
        ),
    ]
